# https://taskfile.dev
---
version: '3'

vars:
  PROJ_DIR: .
  VENV_DIR: '.venv-py3-local'
  PYTHON_VERSION: '3.12'
  NAUTOBOT_VERSION: '2.4.7'

tasks:
  setup:
    silent: true
    dir: '{{.ROOT_TASKFILE}}'
    cmds:
      - pwd
      - #- - - Creating a virtual python environment - - -
      - which python3
      - python3 -m venv {{.VENV_DIR}}
      - #- - - Installing local python dependecies - - -
      - |
        echo ------------------------------------------------------------
        source {{.VENV_DIR}}/bin/activate
        python --version
        python -m pip install --upgrade pip invoke toml
        pip --version
        invoke --version
      - docker --version
      - docker compose version

  pull:
    silent: true
    vars:
      REGISTRY: ghcr.io/nautobot/nautobot
    cmds:
      - |
        echo ------------------------------------------------------------
        echo '{{.REGISTRY}}:{{.NAUTOBOT_VERSION}}-py{{.PYTHON_VERSION}}'
        echo ------------------------------------------------------------
        docker pull '{{.REGISTRY}}:{{.NAUTOBOT_VERSION}}-py{{.PYTHON_VERSION}}'
        echo ------------------------------------------------------------
        echo '{{.REGISTRY}}dev:{{.NAUTOBOT_VERSION}}-py{{.PYTHON_VERSION}}'
        echo ------------------------------------------------------------
        docker pull '{{.REGISTRY}}-dev:{{.NAUTOBOT_VERSION}}-py{{.PYTHON_VERSION}}'

  build:
    silent: true
    env:
      INVOKE_NETWORKTOCODE_NAUTOBOT_VERSION: '{{.NAUTOBOT_VERSION}}'
      INVOKE_NETWORKTOCODE_PYTHON_VERSION: '{{.PYTHON_VERSION}}'
      INVOKE_NETWORKTOCODE_IMAGE_NAME: 'oliverhr/nautobot-development'
    dir: '{{.ROOT_TASKFILE}}/{{.PROJ_DIR}}'
    preconditions:
      - test -d ../{{.PROJ_DIR}}
      - test -d ../{{.VENV_DIR}}
      - test -f invoke.yml
    cmds:
      - |
        echo ------------------------------------------------------------
        pwd
        ls -l
        source ../{{.VENV_DIR}}/bin/activate
        echo ------------------------------------------------------------
        invoke build
        echo ------------------------------------------------------------
      - docker image ls

  deploy:
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test true
    cmds:
      - |
        echo ------------------------------------------------------------
        pwd
        echo Deploy images to target server
        echo ------------------------------------------------------------

# vim: set ft=yaml ts=2 sw=2 et nowrap :
